### ISSUE TITLE
missing dependencies: react & react-dom

### ISSUE THREAD

**Issue by nksfrank** [merisbahti/klyva#26]
the source code in "react-utils.ts" is importing and using both `react` and `react-dom` packages directly, but these packages are not included in the `dependency` field in your `package.json` (they are however located in  `devDependencies`).

you could add them under `peerDependencies` field as `^16.8.3` to allow the end user to supply their own react/react-dom version from their project

**Comment by merisbahti** [comment]
Hey @nksfrank , thanks for your issue!

You suppose this would fix it?
https://github.com/merisbahti/klyva/pull/27

**Comment by merisbahti** [comment]
I was testing this stuff around in some of my projects and it works really good, thanks for the help!
